// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testServer.proto

package so.sao.test.protobuf;

public final class TestServer {
  private TestServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code PhoneType}
   */
  public enum PhoneType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HOME = 0;</code>
     */
    HOME(0),
    /**
     * <code>WORK = 1;</code>
     */
    WORK(1),
    /**
     * <code>OTHOR = 2;</code>
     */
    OTHOR(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>HOME = 0;</code>
     */
    public static final int HOME_VALUE = 0;
    /**
     * <code>WORK = 1;</code>
     */
    public static final int WORK_VALUE = 1;
    /**
     * <code>OTHOR = 2;</code>
     */
    public static final int OTHOR_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PhoneType valueOf(int value) {
      return forNumber(value);
    }

    public static PhoneType forNumber(int value) {
      switch (value) {
        case 0: return HOME;
        case 1: return WORK;
        case 2: return OTHOR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PhoneType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
            public PhoneType findValueByNumber(int number) {
              return PhoneType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return so.sao.test.protobuf.TestServer.getDescriptor().getEnumTypes().get(0);
    }

    private static final PhoneType[] VALUES = values();

    public static PhoneType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PhoneType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PhoneType)
  }

  public interface ProtobufUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtobufUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    java.util.List<so.sao.test.protobuf.TestServer.ProtobufUser.Phone> 
        getPhonesList();
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    so.sao.test.protobuf.TestServer.ProtobufUser.Phone getPhones(int index);
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    int getPhonesCount();
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    java.util.List<? extends so.sao.test.protobuf.TestServer.ProtobufUser.PhoneOrBuilder> 
        getPhonesOrBuilderList();
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    so.sao.test.protobuf.TestServer.ProtobufUser.PhoneOrBuilder getPhonesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ProtobufUser}
   */
  public  static final class ProtobufUser extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProtobufUser)
      ProtobufUserOrBuilder {
    // Use ProtobufUser.newBuilder() to construct.
    private ProtobufUser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtobufUser() {
      id_ = 0;
      name_ = "";
      phones_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProtobufUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                phones_ = new java.util.ArrayList<so.sao.test.protobuf.TestServer.ProtobufUser.Phone>();
                mutable_bitField0_ |= 0x00000004;
              }
              phones_.add(
                  input.readMessage(so.sao.test.protobuf.TestServer.ProtobufUser.Phone.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          phones_ = java.util.Collections.unmodifiableList(phones_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return so.sao.test.protobuf.TestServer.internal_static_ProtobufUser_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return so.sao.test.protobuf.TestServer.internal_static_ProtobufUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              so.sao.test.protobuf.TestServer.ProtobufUser.class, so.sao.test.protobuf.TestServer.ProtobufUser.Builder.class);
    }

    public interface PhoneOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ProtobufUser.Phone)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional .PhoneType phoneType = 1;</code>
       */
      int getPhoneTypeValue();
      /**
       * <code>optional .PhoneType phoneType = 1;</code>
       */
      so.sao.test.protobuf.TestServer.PhoneType getPhoneType();

      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      java.lang.String getPhoneNumber();
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      com.google.protobuf.ByteString
          getPhoneNumberBytes();
    }
    /**
     * Protobuf type {@code ProtobufUser.Phone}
     */
    public  static final class Phone extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ProtobufUser.Phone)
        PhoneOrBuilder {
      // Use Phone.newBuilder() to construct.
      private Phone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Phone() {
        phoneType_ = 0;
        phoneNumber_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Phone(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();

                phoneType_ = rawValue;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                phoneNumber_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return so.sao.test.protobuf.TestServer.internal_static_ProtobufUser_Phone_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return so.sao.test.protobuf.TestServer.internal_static_ProtobufUser_Phone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                so.sao.test.protobuf.TestServer.ProtobufUser.Phone.class, so.sao.test.protobuf.TestServer.ProtobufUser.Phone.Builder.class);
      }

      public static final int PHONETYPE_FIELD_NUMBER = 1;
      private int phoneType_;
      /**
       * <code>optional .PhoneType phoneType = 1;</code>
       */
      public int getPhoneTypeValue() {
        return phoneType_;
      }
      /**
       * <code>optional .PhoneType phoneType = 1;</code>
       */
      public so.sao.test.protobuf.TestServer.PhoneType getPhoneType() {
        so.sao.test.protobuf.TestServer.PhoneType result = so.sao.test.protobuf.TestServer.PhoneType.valueOf(phoneType_);
        return result == null ? so.sao.test.protobuf.TestServer.PhoneType.UNRECOGNIZED : result;
      }

      public static final int PHONENUMBER_FIELD_NUMBER = 2;
      private volatile java.lang.Object phoneNumber_;
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      public java.lang.String getPhoneNumber() {
        java.lang.Object ref = phoneNumber_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneNumber_ = s;
          return s;
        }
      }
      /**
       * <code>optional string phoneNumber = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes() {
        java.lang.Object ref = phoneNumber_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (phoneType_ != so.sao.test.protobuf.TestServer.PhoneType.HOME.getNumber()) {
          output.writeEnum(1, phoneType_);
        }
        if (!getPhoneNumberBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, phoneNumber_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (phoneType_ != so.sao.test.protobuf.TestServer.PhoneType.HOME.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, phoneType_);
        }
        if (!getPhoneNumberBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, phoneNumber_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof so.sao.test.protobuf.TestServer.ProtobufUser.Phone)) {
          return super.equals(obj);
        }
        so.sao.test.protobuf.TestServer.ProtobufUser.Phone other = (so.sao.test.protobuf.TestServer.ProtobufUser.Phone) obj;

        boolean result = true;
        result = result && phoneType_ == other.phoneType_;
        result = result && getPhoneNumber()
            .equals(other.getPhoneNumber());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + PHONETYPE_FIELD_NUMBER;
        hash = (53 * hash) + phoneType_;
        hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneNumber().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static so.sao.test.protobuf.TestServer.ProtobufUser.Phone parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static so.sao.test.protobuf.TestServer.ProtobufUser.Phone parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static so.sao.test.protobuf.TestServer.ProtobufUser.Phone parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static so.sao.test.protobuf.TestServer.ProtobufUser.Phone parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static so.sao.test.protobuf.TestServer.ProtobufUser.Phone parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static so.sao.test.protobuf.TestServer.ProtobufUser.Phone parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static so.sao.test.protobuf.TestServer.ProtobufUser.Phone parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static so.sao.test.protobuf.TestServer.ProtobufUser.Phone parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static so.sao.test.protobuf.TestServer.ProtobufUser.Phone parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static so.sao.test.protobuf.TestServer.ProtobufUser.Phone parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(so.sao.test.protobuf.TestServer.ProtobufUser.Phone prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ProtobufUser.Phone}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ProtobufUser.Phone)
          so.sao.test.protobuf.TestServer.ProtobufUser.PhoneOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return so.sao.test.protobuf.TestServer.internal_static_ProtobufUser_Phone_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return so.sao.test.protobuf.TestServer.internal_static_ProtobufUser_Phone_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  so.sao.test.protobuf.TestServer.ProtobufUser.Phone.class, so.sao.test.protobuf.TestServer.ProtobufUser.Phone.Builder.class);
        }

        // Construct using so.sao.test.protobuf.TestServer.ProtobufUser.Phone.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          phoneType_ = 0;

          phoneNumber_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return so.sao.test.protobuf.TestServer.internal_static_ProtobufUser_Phone_descriptor;
        }

        public so.sao.test.protobuf.TestServer.ProtobufUser.Phone getDefaultInstanceForType() {
          return so.sao.test.protobuf.TestServer.ProtobufUser.Phone.getDefaultInstance();
        }

        public so.sao.test.protobuf.TestServer.ProtobufUser.Phone build() {
          so.sao.test.protobuf.TestServer.ProtobufUser.Phone result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public so.sao.test.protobuf.TestServer.ProtobufUser.Phone buildPartial() {
          so.sao.test.protobuf.TestServer.ProtobufUser.Phone result = new so.sao.test.protobuf.TestServer.ProtobufUser.Phone(this);
          result.phoneType_ = phoneType_;
          result.phoneNumber_ = phoneNumber_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof so.sao.test.protobuf.TestServer.ProtobufUser.Phone) {
            return mergeFrom((so.sao.test.protobuf.TestServer.ProtobufUser.Phone)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(so.sao.test.protobuf.TestServer.ProtobufUser.Phone other) {
          if (other == so.sao.test.protobuf.TestServer.ProtobufUser.Phone.getDefaultInstance()) return this;
          if (other.phoneType_ != 0) {
            setPhoneTypeValue(other.getPhoneTypeValue());
          }
          if (!other.getPhoneNumber().isEmpty()) {
            phoneNumber_ = other.phoneNumber_;
            onChanged();
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          so.sao.test.protobuf.TestServer.ProtobufUser.Phone parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (so.sao.test.protobuf.TestServer.ProtobufUser.Phone) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int phoneType_ = 0;
        /**
         * <code>optional .PhoneType phoneType = 1;</code>
         */
        public int getPhoneTypeValue() {
          return phoneType_;
        }
        /**
         * <code>optional .PhoneType phoneType = 1;</code>
         */
        public Builder setPhoneTypeValue(int value) {
          phoneType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .PhoneType phoneType = 1;</code>
         */
        public so.sao.test.protobuf.TestServer.PhoneType getPhoneType() {
          so.sao.test.protobuf.TestServer.PhoneType result = so.sao.test.protobuf.TestServer.PhoneType.valueOf(phoneType_);
          return result == null ? so.sao.test.protobuf.TestServer.PhoneType.UNRECOGNIZED : result;
        }
        /**
         * <code>optional .PhoneType phoneType = 1;</code>
         */
        public Builder setPhoneType(so.sao.test.protobuf.TestServer.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          phoneType_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .PhoneType phoneType = 1;</code>
         */
        public Builder clearPhoneType() {
          
          phoneType_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object phoneNumber_ = "";
        /**
         * <code>optional string phoneNumber = 2;</code>
         */
        public java.lang.String getPhoneNumber() {
          java.lang.Object ref = phoneNumber_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            phoneNumber_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string phoneNumber = 2;</code>
         */
        public com.google.protobuf.ByteString
            getPhoneNumberBytes() {
          java.lang.Object ref = phoneNumber_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            phoneNumber_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string phoneNumber = 2;</code>
         */
        public Builder setPhoneNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          phoneNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string phoneNumber = 2;</code>
         */
        public Builder clearPhoneNumber() {
          
          phoneNumber_ = getDefaultInstance().getPhoneNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional string phoneNumber = 2;</code>
         */
        public Builder setPhoneNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          phoneNumber_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:ProtobufUser.Phone)
      }

      // @@protoc_insertion_point(class_scope:ProtobufUser.Phone)
      private static final so.sao.test.protobuf.TestServer.ProtobufUser.Phone DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new so.sao.test.protobuf.TestServer.ProtobufUser.Phone();
      }

      public static so.sao.test.protobuf.TestServer.ProtobufUser.Phone getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Phone>
          PARSER = new com.google.protobuf.AbstractParser<Phone>() {
        public Phone parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Phone(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Phone> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Phone> getParserForType() {
        return PARSER;
      }

      public so.sao.test.protobuf.TestServer.ProtobufUser.Phone getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHONES_FIELD_NUMBER = 3;
    private java.util.List<so.sao.test.protobuf.TestServer.ProtobufUser.Phone> phones_;
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    public java.util.List<so.sao.test.protobuf.TestServer.ProtobufUser.Phone> getPhonesList() {
      return phones_;
    }
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    public java.util.List<? extends so.sao.test.protobuf.TestServer.ProtobufUser.PhoneOrBuilder> 
        getPhonesOrBuilderList() {
      return phones_;
    }
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    public so.sao.test.protobuf.TestServer.ProtobufUser.Phone getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <code>repeated .ProtobufUser.Phone phones = 3;</code>
     */
    public so.sao.test.protobuf.TestServer.ProtobufUser.PhoneOrBuilder getPhonesOrBuilder(
        int index) {
      return phones_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < phones_.size(); i++) {
        output.writeMessage(3, phones_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      for (int i = 0; i < phones_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, phones_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof so.sao.test.protobuf.TestServer.ProtobufUser)) {
        return super.equals(obj);
      }
      so.sao.test.protobuf.TestServer.ProtobufUser other = (so.sao.test.protobuf.TestServer.ProtobufUser) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getPhonesList()
          .equals(other.getPhonesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getPhonesCount() > 0) {
        hash = (37 * hash) + PHONES_FIELD_NUMBER;
        hash = (53 * hash) + getPhonesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static so.sao.test.protobuf.TestServer.ProtobufUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static so.sao.test.protobuf.TestServer.ProtobufUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.ProtobufUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static so.sao.test.protobuf.TestServer.ProtobufUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.ProtobufUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.ProtobufUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.ProtobufUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.ProtobufUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.ProtobufUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.ProtobufUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(so.sao.test.protobuf.TestServer.ProtobufUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtobufUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtobufUser)
        so.sao.test.protobuf.TestServer.ProtobufUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return so.sao.test.protobuf.TestServer.internal_static_ProtobufUser_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return so.sao.test.protobuf.TestServer.internal_static_ProtobufUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                so.sao.test.protobuf.TestServer.ProtobufUser.class, so.sao.test.protobuf.TestServer.ProtobufUser.Builder.class);
      }

      // Construct using so.sao.test.protobuf.TestServer.ProtobufUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPhonesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        if (phonesBuilder_ == null) {
          phones_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          phonesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return so.sao.test.protobuf.TestServer.internal_static_ProtobufUser_descriptor;
      }

      public so.sao.test.protobuf.TestServer.ProtobufUser getDefaultInstanceForType() {
        return so.sao.test.protobuf.TestServer.ProtobufUser.getDefaultInstance();
      }

      public so.sao.test.protobuf.TestServer.ProtobufUser build() {
        so.sao.test.protobuf.TestServer.ProtobufUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public so.sao.test.protobuf.TestServer.ProtobufUser buildPartial() {
        so.sao.test.protobuf.TestServer.ProtobufUser result = new so.sao.test.protobuf.TestServer.ProtobufUser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        if (phonesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            phones_ = java.util.Collections.unmodifiableList(phones_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.phones_ = phones_;
        } else {
          result.phones_ = phonesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof so.sao.test.protobuf.TestServer.ProtobufUser) {
          return mergeFrom((so.sao.test.protobuf.TestServer.ProtobufUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(so.sao.test.protobuf.TestServer.ProtobufUser other) {
        if (other == so.sao.test.protobuf.TestServer.ProtobufUser.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (phonesBuilder_ == null) {
          if (!other.phones_.isEmpty()) {
            if (phones_.isEmpty()) {
              phones_ = other.phones_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePhonesIsMutable();
              phones_.addAll(other.phones_);
            }
            onChanged();
          }
        } else {
          if (!other.phones_.isEmpty()) {
            if (phonesBuilder_.isEmpty()) {
              phonesBuilder_.dispose();
              phonesBuilder_ = null;
              phones_ = other.phones_;
              bitField0_ = (bitField0_ & ~0x00000004);
              phonesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPhonesFieldBuilder() : null;
            } else {
              phonesBuilder_.addAllMessages(other.phones_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        so.sao.test.protobuf.TestServer.ProtobufUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (so.sao.test.protobuf.TestServer.ProtobufUser) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<so.sao.test.protobuf.TestServer.ProtobufUser.Phone> phones_ =
        java.util.Collections.emptyList();
      private void ensurePhonesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          phones_ = new java.util.ArrayList<so.sao.test.protobuf.TestServer.ProtobufUser.Phone>(phones_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          so.sao.test.protobuf.TestServer.ProtobufUser.Phone, so.sao.test.protobuf.TestServer.ProtobufUser.Phone.Builder, so.sao.test.protobuf.TestServer.ProtobufUser.PhoneOrBuilder> phonesBuilder_;

      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public java.util.List<so.sao.test.protobuf.TestServer.ProtobufUser.Phone> getPhonesList() {
        if (phonesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phones_);
        } else {
          return phonesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public int getPhonesCount() {
        if (phonesBuilder_ == null) {
          return phones_.size();
        } else {
          return phonesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public so.sao.test.protobuf.TestServer.ProtobufUser.Phone getPhones(int index) {
        if (phonesBuilder_ == null) {
          return phones_.get(index);
        } else {
          return phonesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder setPhones(
          int index, so.sao.test.protobuf.TestServer.ProtobufUser.Phone value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.set(index, value);
          onChanged();
        } else {
          phonesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder setPhones(
          int index, so.sao.test.protobuf.TestServer.ProtobufUser.Phone.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.set(index, builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder addPhones(so.sao.test.protobuf.TestServer.ProtobufUser.Phone value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.add(value);
          onChanged();
        } else {
          phonesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder addPhones(
          int index, so.sao.test.protobuf.TestServer.ProtobufUser.Phone value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.add(index, value);
          onChanged();
        } else {
          phonesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder addPhones(
          so.sao.test.protobuf.TestServer.ProtobufUser.Phone.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.add(builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder addPhones(
          int index, so.sao.test.protobuf.TestServer.ProtobufUser.Phone.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.add(index, builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder addAllPhones(
          java.lang.Iterable<? extends so.sao.test.protobuf.TestServer.ProtobufUser.Phone> values) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, phones_);
          onChanged();
        } else {
          phonesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder clearPhones() {
        if (phonesBuilder_ == null) {
          phones_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          phonesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public Builder removePhones(int index) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.remove(index);
          onChanged();
        } else {
          phonesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public so.sao.test.protobuf.TestServer.ProtobufUser.Phone.Builder getPhonesBuilder(
          int index) {
        return getPhonesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public so.sao.test.protobuf.TestServer.ProtobufUser.PhoneOrBuilder getPhonesOrBuilder(
          int index) {
        if (phonesBuilder_ == null) {
          return phones_.get(index);  } else {
          return phonesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public java.util.List<? extends so.sao.test.protobuf.TestServer.ProtobufUser.PhoneOrBuilder> 
           getPhonesOrBuilderList() {
        if (phonesBuilder_ != null) {
          return phonesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phones_);
        }
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public so.sao.test.protobuf.TestServer.ProtobufUser.Phone.Builder addPhonesBuilder() {
        return getPhonesFieldBuilder().addBuilder(
            so.sao.test.protobuf.TestServer.ProtobufUser.Phone.getDefaultInstance());
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public so.sao.test.protobuf.TestServer.ProtobufUser.Phone.Builder addPhonesBuilder(
          int index) {
        return getPhonesFieldBuilder().addBuilder(
            index, so.sao.test.protobuf.TestServer.ProtobufUser.Phone.getDefaultInstance());
      }
      /**
       * <code>repeated .ProtobufUser.Phone phones = 3;</code>
       */
      public java.util.List<so.sao.test.protobuf.TestServer.ProtobufUser.Phone.Builder> 
           getPhonesBuilderList() {
        return getPhonesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          so.sao.test.protobuf.TestServer.ProtobufUser.Phone, so.sao.test.protobuf.TestServer.ProtobufUser.Phone.Builder, so.sao.test.protobuf.TestServer.ProtobufUser.PhoneOrBuilder> 
          getPhonesFieldBuilder() {
        if (phonesBuilder_ == null) {
          phonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              so.sao.test.protobuf.TestServer.ProtobufUser.Phone, so.sao.test.protobuf.TestServer.ProtobufUser.Phone.Builder, so.sao.test.protobuf.TestServer.ProtobufUser.PhoneOrBuilder>(
                  phones_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          phones_ = null;
        }
        return phonesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ProtobufUser)
    }

    // @@protoc_insertion_point(class_scope:ProtobufUser)
    private static final so.sao.test.protobuf.TestServer.ProtobufUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new so.sao.test.protobuf.TestServer.ProtobufUser();
    }

    public static so.sao.test.protobuf.TestServer.ProtobufUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtobufUser>
        PARSER = new com.google.protobuf.AbstractParser<ProtobufUser>() {
      public ProtobufUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProtobufUser(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtobufUser> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtobufUser> getParserForType() {
      return PARSER;
    }

    public so.sao.test.protobuf.TestServer.ProtobufUser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddPhoneToUserRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddPhoneToUserRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 uid = 1;</code>
     */
    int getUid();

    /**
     * <code>optional .PhoneType phoneType = 2;</code>
     */
    int getPhoneTypeValue();
    /**
     * <code>optional .PhoneType phoneType = 2;</code>
     */
    so.sao.test.protobuf.TestServer.PhoneType getPhoneType();

    /**
     * <code>optional string phoneNumber = 3;</code>
     */
    java.lang.String getPhoneNumber();
    /**
     * <code>optional string phoneNumber = 3;</code>
     */
    com.google.protobuf.ByteString
        getPhoneNumberBytes();
  }
  /**
   * Protobuf type {@code AddPhoneToUserRequest}
   */
  public  static final class AddPhoneToUserRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddPhoneToUserRequest)
      AddPhoneToUserRequestOrBuilder {
    // Use AddPhoneToUserRequest.newBuilder() to construct.
    private AddPhoneToUserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddPhoneToUserRequest() {
      uid_ = 0;
      phoneType_ = 0;
      phoneNumber_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AddPhoneToUserRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              uid_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              phoneType_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              phoneNumber_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              so.sao.test.protobuf.TestServer.AddPhoneToUserRequest.class, so.sao.test.protobuf.TestServer.AddPhoneToUserRequest.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>optional int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int PHONETYPE_FIELD_NUMBER = 2;
    private int phoneType_;
    /**
     * <code>optional .PhoneType phoneType = 2;</code>
     */
    public int getPhoneTypeValue() {
      return phoneType_;
    }
    /**
     * <code>optional .PhoneType phoneType = 2;</code>
     */
    public so.sao.test.protobuf.TestServer.PhoneType getPhoneType() {
      so.sao.test.protobuf.TestServer.PhoneType result = so.sao.test.protobuf.TestServer.PhoneType.valueOf(phoneType_);
      return result == null ? so.sao.test.protobuf.TestServer.PhoneType.UNRECOGNIZED : result;
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 3;
    private volatile java.lang.Object phoneNumber_;
    /**
     * <code>optional string phoneNumber = 3;</code>
     */
    public java.lang.String getPhoneNumber() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneNumber_ = s;
        return s;
      }
    }
    /**
     * <code>optional string phoneNumber = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0) {
        output.writeInt32(1, uid_);
      }
      if (phoneType_ != so.sao.test.protobuf.TestServer.PhoneType.HOME.getNumber()) {
        output.writeEnum(2, phoneType_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phoneNumber_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (phoneType_ != so.sao.test.protobuf.TestServer.PhoneType.HOME.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, phoneType_);
      }
      if (!getPhoneNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phoneNumber_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof so.sao.test.protobuf.TestServer.AddPhoneToUserRequest)) {
        return super.equals(obj);
      }
      so.sao.test.protobuf.TestServer.AddPhoneToUserRequest other = (so.sao.test.protobuf.TestServer.AddPhoneToUserRequest) obj;

      boolean result = true;
      result = result && (getUid()
          == other.getUid());
      result = result && phoneType_ == other.phoneType_;
      result = result && getPhoneNumber()
          .equals(other.getPhoneNumber());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (37 * hash) + PHONETYPE_FIELD_NUMBER;
      hash = (53 * hash) + phoneType_;
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumber().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(so.sao.test.protobuf.TestServer.AddPhoneToUserRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddPhoneToUserRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddPhoneToUserRequest)
        so.sao.test.protobuf.TestServer.AddPhoneToUserRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                so.sao.test.protobuf.TestServer.AddPhoneToUserRequest.class, so.sao.test.protobuf.TestServer.AddPhoneToUserRequest.Builder.class);
      }

      // Construct using so.sao.test.protobuf.TestServer.AddPhoneToUserRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = 0;

        phoneType_ = 0;

        phoneNumber_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserRequest_descriptor;
      }

      public so.sao.test.protobuf.TestServer.AddPhoneToUserRequest getDefaultInstanceForType() {
        return so.sao.test.protobuf.TestServer.AddPhoneToUserRequest.getDefaultInstance();
      }

      public so.sao.test.protobuf.TestServer.AddPhoneToUserRequest build() {
        so.sao.test.protobuf.TestServer.AddPhoneToUserRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public so.sao.test.protobuf.TestServer.AddPhoneToUserRequest buildPartial() {
        so.sao.test.protobuf.TestServer.AddPhoneToUserRequest result = new so.sao.test.protobuf.TestServer.AddPhoneToUserRequest(this);
        result.uid_ = uid_;
        result.phoneType_ = phoneType_;
        result.phoneNumber_ = phoneNumber_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof so.sao.test.protobuf.TestServer.AddPhoneToUserRequest) {
          return mergeFrom((so.sao.test.protobuf.TestServer.AddPhoneToUserRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(so.sao.test.protobuf.TestServer.AddPhoneToUserRequest other) {
        if (other == so.sao.test.protobuf.TestServer.AddPhoneToUserRequest.getDefaultInstance()) return this;
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (other.phoneType_ != 0) {
          setPhoneTypeValue(other.getPhoneTypeValue());
        }
        if (!other.getPhoneNumber().isEmpty()) {
          phoneNumber_ = other.phoneNumber_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        so.sao.test.protobuf.TestServer.AddPhoneToUserRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (so.sao.test.protobuf.TestServer.AddPhoneToUserRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uid_ ;
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }

      private int phoneType_ = 0;
      /**
       * <code>optional .PhoneType phoneType = 2;</code>
       */
      public int getPhoneTypeValue() {
        return phoneType_;
      }
      /**
       * <code>optional .PhoneType phoneType = 2;</code>
       */
      public Builder setPhoneTypeValue(int value) {
        phoneType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .PhoneType phoneType = 2;</code>
       */
      public so.sao.test.protobuf.TestServer.PhoneType getPhoneType() {
        so.sao.test.protobuf.TestServer.PhoneType result = so.sao.test.protobuf.TestServer.PhoneType.valueOf(phoneType_);
        return result == null ? so.sao.test.protobuf.TestServer.PhoneType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .PhoneType phoneType = 2;</code>
       */
      public Builder setPhoneType(so.sao.test.protobuf.TestServer.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        phoneType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .PhoneType phoneType = 2;</code>
       */
      public Builder clearPhoneType() {
        
        phoneType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object phoneNumber_ = "";
      /**
       * <code>optional string phoneNumber = 3;</code>
       */
      public java.lang.String getPhoneNumber() {
        java.lang.Object ref = phoneNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string phoneNumber = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneNumberBytes() {
        java.lang.Object ref = phoneNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phoneNumber = 3;</code>
       */
      public Builder setPhoneNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phoneNumber = 3;</code>
       */
      public Builder clearPhoneNumber() {
        
        phoneNumber_ = getDefaultInstance().getPhoneNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phoneNumber = 3;</code>
       */
      public Builder setPhoneNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AddPhoneToUserRequest)
    }

    // @@protoc_insertion_point(class_scope:AddPhoneToUserRequest)
    private static final so.sao.test.protobuf.TestServer.AddPhoneToUserRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new so.sao.test.protobuf.TestServer.AddPhoneToUserRequest();
    }

    public static so.sao.test.protobuf.TestServer.AddPhoneToUserRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddPhoneToUserRequest>
        PARSER = new com.google.protobuf.AbstractParser<AddPhoneToUserRequest>() {
      public AddPhoneToUserRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AddPhoneToUserRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddPhoneToUserRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddPhoneToUserRequest> getParserForType() {
      return PARSER;
    }

    public so.sao.test.protobuf.TestServer.AddPhoneToUserRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddPhoneToUserResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddPhoneToUserResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool result = 1;</code>
     */
    boolean getResult();
  }
  /**
   * Protobuf type {@code AddPhoneToUserResponse}
   */
  public  static final class AddPhoneToUserResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddPhoneToUserResponse)
      AddPhoneToUserResponseOrBuilder {
    // Use AddPhoneToUserResponse.newBuilder() to construct.
    private AddPhoneToUserResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddPhoneToUserResponse() {
      result_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AddPhoneToUserResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              result_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              so.sao.test.protobuf.TestServer.AddPhoneToUserResponse.class, so.sao.test.protobuf.TestServer.AddPhoneToUserResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean result_;
    /**
     * <code>optional bool result = 1;</code>
     */
    public boolean getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != false) {
        output.writeBool(1, result_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, result_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof so.sao.test.protobuf.TestServer.AddPhoneToUserResponse)) {
        return super.equals(obj);
      }
      so.sao.test.protobuf.TestServer.AddPhoneToUserResponse other = (so.sao.test.protobuf.TestServer.AddPhoneToUserResponse) obj;

      boolean result = true;
      result = result && (getResult()
          == other.getResult());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getResult());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(so.sao.test.protobuf.TestServer.AddPhoneToUserResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddPhoneToUserResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddPhoneToUserResponse)
        so.sao.test.protobuf.TestServer.AddPhoneToUserResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                so.sao.test.protobuf.TestServer.AddPhoneToUserResponse.class, so.sao.test.protobuf.TestServer.AddPhoneToUserResponse.Builder.class);
      }

      // Construct using so.sao.test.protobuf.TestServer.AddPhoneToUserResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        result_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return so.sao.test.protobuf.TestServer.internal_static_AddPhoneToUserResponse_descriptor;
      }

      public so.sao.test.protobuf.TestServer.AddPhoneToUserResponse getDefaultInstanceForType() {
        return so.sao.test.protobuf.TestServer.AddPhoneToUserResponse.getDefaultInstance();
      }

      public so.sao.test.protobuf.TestServer.AddPhoneToUserResponse build() {
        so.sao.test.protobuf.TestServer.AddPhoneToUserResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public so.sao.test.protobuf.TestServer.AddPhoneToUserResponse buildPartial() {
        so.sao.test.protobuf.TestServer.AddPhoneToUserResponse result = new so.sao.test.protobuf.TestServer.AddPhoneToUserResponse(this);
        result.result_ = result_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof so.sao.test.protobuf.TestServer.AddPhoneToUserResponse) {
          return mergeFrom((so.sao.test.protobuf.TestServer.AddPhoneToUserResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(so.sao.test.protobuf.TestServer.AddPhoneToUserResponse other) {
        if (other == so.sao.test.protobuf.TestServer.AddPhoneToUserResponse.getDefaultInstance()) return this;
        if (other.getResult() != false) {
          setResult(other.getResult());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        so.sao.test.protobuf.TestServer.AddPhoneToUserResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (so.sao.test.protobuf.TestServer.AddPhoneToUserResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean result_ ;
      /**
       * <code>optional bool result = 1;</code>
       */
      public boolean getResult() {
        return result_;
      }
      /**
       * <code>optional bool result = 1;</code>
       */
      public Builder setResult(boolean value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AddPhoneToUserResponse)
    }

    // @@protoc_insertion_point(class_scope:AddPhoneToUserResponse)
    private static final so.sao.test.protobuf.TestServer.AddPhoneToUserResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new so.sao.test.protobuf.TestServer.AddPhoneToUserResponse();
    }

    public static so.sao.test.protobuf.TestServer.AddPhoneToUserResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddPhoneToUserResponse>
        PARSER = new com.google.protobuf.AbstractParser<AddPhoneToUserResponse>() {
      public AddPhoneToUserResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AddPhoneToUserResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddPhoneToUserResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddPhoneToUserResponse> getParserForType() {
      return PARSER;
    }

    public so.sao.test.protobuf.TestServer.AddPhoneToUserResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtobufUser_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtobufUser_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtobufUser_Phone_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtobufUser_Phone_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddPhoneToUserRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddPhoneToUserRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddPhoneToUserResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddPhoneToUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020testServer.proto\"\212\001\n\014ProtobufUser\022\n\n\002i" +
      "d\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022#\n\006phones\030\003 \003(\0132\023." +
      "ProtobufUser.Phone\032;\n\005Phone\022\035\n\tphoneType" +
      "\030\001 \001(\0162\n.PhoneType\022\023\n\013phoneNumber\030\002 \001(\t\"" +
      "X\n\025AddPhoneToUserRequest\022\013\n\003uid\030\001 \001(\005\022\035\n" +
      "\tphoneType\030\002 \001(\0162\n.PhoneType\022\023\n\013phoneNum" +
      "ber\030\003 \001(\t\"(\n\026AddPhoneToUserResponse\022\016\n\006r" +
      "esult\030\001 \001(\010**\n\tPhoneType\022\010\n\004HOME\020\000\022\010\n\004WO" +
      "RK\020\001\022\t\n\005OTHOR\020\0022Q\n\014PhoneService\022A\n\016addPh" +
      "oneToUser\022\026.AddPhoneToUserRequest\032\027.AddP",
      "honeToUserResponseB\026\n\024so.sao.test.protob" +
      "ufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProtobufUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtobufUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtobufUser_descriptor,
        new java.lang.String[] { "Id", "Name", "Phones", });
    internal_static_ProtobufUser_Phone_descriptor =
      internal_static_ProtobufUser_descriptor.getNestedTypes().get(0);
    internal_static_ProtobufUser_Phone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtobufUser_Phone_descriptor,
        new java.lang.String[] { "PhoneType", "PhoneNumber", });
    internal_static_AddPhoneToUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddPhoneToUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddPhoneToUserRequest_descriptor,
        new java.lang.String[] { "Uid", "PhoneType", "PhoneNumber", });
    internal_static_AddPhoneToUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AddPhoneToUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddPhoneToUserResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
